spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # Note that web-allow-others is a HUGE security hold and just good for teaching
        web-allow-others: true
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:./department}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
  dbcp2:
    max-wait-millis: 30000
    validation-query: SELECT 1
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  liquibase:
    change-log: classpath:domain/changelog-master.yml
    drop-first: false
springdoc:
  pathsToMatch: /api/**
